# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: 名称：Gradle 包

on:
  release:
    types: [    类型：[已创建]]

jobs:
  build:

    runs-on:     运行于：ubuntu-latest
    permissions:
      contents:       内容：已读
      packages:       包：写入

    steps:
    - uses:     - 使用：actions/checkout@v4
    - name:     - 名称：设置 JDK 17
      uses:       用途：actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id:         server-id: github # pom.xml 的 distributionManagement/repository/id 字段的值# Value of the distributionManagement/repository/id field of the pom.xml
        settings-path:         settings-path: ${{ github.workspace }} # settings.xml 文件的位置{{ github.workspace }} # location for the settings.xml file

    - name:     - 名称：设置 Gradle
      uses:       使用：gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5#v3.1.0# v3.1.0

    - name:     - 名称：使用 Gradle 构建
      run:       运行：./gradlew build

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
